/// 
Class rhc.utils.NewProcess1 Extends Ens.BusinessProcessBPL [ ClassType = persistent, ProcedureBlock ]
{

/// BPL Definition
XData BPL [ XMLNamespace = "http://www.intersystems.com/bpl" ]
{
<process language='objectscript' request='Ens.Request' response='Ens.Response' height='2000' width='2000' >
<sequence xend='199' yend='349' >
<empty xpos='539' ypos='253' />
</sequence>
</process>
}

Storage Default
{
<Type>%Library.CacheStorage</Type>
}

}
